stages:
  - deploy

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCeEp0Smy1u0ggHtY1Xm3HbotdLpVkXCQ6PFUib2NNZC+XMDDdNl9ogjCj0XedxnQqMe5S9RAYY6t6oHach9BA9So+V5XubJ/ZujtsOA6VHm/HzAMKKs+Ha7bnLLd8csuXtBy7t6M23bK9K+aUplq5x8WyHzRhh9bJVqX8M186+jAG0R+YNR1Yp/+OTtBsl68ewH8lGXGn2nc9U1RcX0RudEa4tkIsD6zMFVM5dHXqg41+u3MUmyPRDto0wUY8i4sLjKGCyySXE12fmObBU8iLan9UBVZYDs7H/NTiLnp7TR9FPhfKUtzeCJX7+j1bKdeKaLBJGYwsWXhNIiVECo7Ahar7usH2NXBokgm7srb5YO3naHDxHv1QVFHxS/BhmoGfPmZi3/xjrxmPAUwKlUyPY7Vegmly7JlGU5H/1U5V4cH638/tL7ZwblUyF6EwIgK4PxgadVqemCwbsJ9f7EbsULIqowGQZwpu6WZ0irodT+209xyoHPLenST8D6XxT+98= ubuntu@ip-172-31-22-28
" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@$52.221.184.221 "git clone git@github.com:mrhoc/harau1.git || true"
    - ssh -o StrictHostKeyChecking=no ubuntu@$52.221.184.221 "cd harau1 && git pull"
    - ssh -o StrictHostKeyChecking=no ubuntu@$52.221.184.221 "cd harau1 && npm i"
    - ssh -o StrictHostKeyChecking=no ubuntu@$52.221.184.221 "cd harau1 && (npm start || true)"
    - echo "Application successfully deployed."
